"""add location_shared to incident_transfers

Revision ID: 29981ad927dd
Revises: f13c10666939
Create Date: 2026-09-09 22:51:41.750978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29981ad927dd'
down_revision: Union[str, Sequence[str], None] = 'f13c10666939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_shared', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_transfers', schema=None) as batch_op:
        batch_op.drop_column('location_shared')

    # ### end Alembic commands ###
