"""add itinerary documents and points of interest

Revision ID: 51c3b736eb77
Revises: 62c707301f67
Create Date: 2026-09-02 21:40:42.499388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c3b736eb77'
down_revision: Union[str, Sequence[str], None] = '62c707301f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_of_interest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_of_interest_category'), ['category'], unique=False)

    op.create_table('itinerary_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('extracted_json', sa.Text(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerary_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_documents_tourist_id'), ['tourist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_documents_tourist_id'))

    op.drop_table('itinerary_documents')
    with op.batch_alter_table('points_of_interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_of_interest_category'))

    op.drop_table('points_of_interest')
    # ### end Alembic commands ###
