"""add police station capacity fields for resource fallback

Revision ID: 62c707301f67
Revises: 3445183755c5
Create Date: 2026-09-02 18:25:12.127843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c707301f67'
down_revision: Union[str, Sequence[str], None] = '3445183755c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('police_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_officers', sa.Integer(), server_default='12', nullable=False))
        batch_op.add_column(sa.Column('max_concurrent_cases', sa.Integer(), server_default='5', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('police_stations', schema=None) as batch_op:
        batch_op.drop_column('max_concurrent_cases')
        batch_op.drop_column('total_officers')

    # ### end Alembic commands ###
