"""add emergency location pings and live tracking flag

Revision ID: 811145802bc1
Revises: eeff8a36fd36
Create Date: 2026-09-05 22:49:54.305017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811145802bc1'
down_revision: Union[str, Sequence[str], None] = 'eeff8a36fd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_location_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_location_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_location_pings_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_location_pings_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_emergency_pings_incident_timestamp', ['incident_id', 'timestamp'], unique=False)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_tracking_active', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('live_tracking_active')

    with op.batch_alter_table('emergency_location_pings', schema=None) as batch_op:
        batch_op.drop_index('ix_emergency_pings_incident_timestamp')
        batch_op.drop_index(batch_op.f('ix_emergency_location_pings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_emergency_location_pings_incident_id'))

    op.drop_table('emergency_location_pings')
    # ### end Alembic commands ###
