"""add unit_type, escalation fields, responder unit link

Revision ID: 818052a0f166
Revises: c1a9e6f3b2d4
Create Date: 2026-08-31 00:12:05.890135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818052a0f166'
down_revision: Union[str, Sequence[str], None] = 'c1a9e6f3b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalation_stage', sa.String(), nullable=False,
                                       server_default='control_room'))
        batch_op.add_column(sa.Column('escalation_deadline', sa.DateTime(), nullable=True))

    with op.batch_alter_table('police_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_type', sa.String(), nullable=False,
                                       server_default='police'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('unit_id')

    with op.batch_alter_table('police_units', schema=None) as batch_op:
        batch_op.drop_column('unit_type')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('escalation_deadline')
        batch_op.drop_column('escalation_stage')

    # ### end Alembic commands ###
