"""add digital tourist safety id: photo, hotel, tokens, scans

Revision ID: 8b8e229d16f8
Revises: fa6501d60f7f
Create Date: 2026-09-01 19:55:02.577736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8b8e229d16f8'
down_revision: Union[str, Sequence[str], None] = 'fa6501d60f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourist_id_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=True),
    sa.Column('scanner_user_id', sa.Integer(), nullable=True),
    sa.Column('scanner_role', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('scan_lat', sa.Float(), nullable=True),
    sa.Column('scan_lng', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('accessed_fields', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scanner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tourist_id_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tourist_id_scans_scanned_at'), ['scanned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tourist_id_scans_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('tourist_id_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('raw_token_encrypted', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tourist_id_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tourist_id_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tourist_id_tokens_tourist_id'), ['tourist_id'], unique=False)

    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hotel', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.drop_column('hotel')
        batch_op.drop_column('photo')

    with op.batch_alter_table('tourist_id_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tourist_id_tokens_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_tourist_id_tokens_token_hash'))

    op.drop_table('tourist_id_tokens')
    with op.batch_alter_table('tourist_id_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tourist_id_scans_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_tourist_id_scans_scanned_at'))

    op.drop_table('tourist_id_scans')
    # ### end Alembic commands ###
