"""add disaster advisories and chain anchors

Revision ID: 8c173d8c1f18
Revises: c48eae9e1233
Create Date: 2026-08-31 14:45:08.250021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c173d8c1f18'
down_revision: Union[str, Sequence[str], None] = 'c48eae9e1233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_anchors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_hash', sa.String(), nullable=False),
    sa.Column('tourist_count', sa.Integer(), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('anchor_target', sa.String(), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chain_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_anchors_created_at'), ['created_at'], unique=False)

    op.create_table('disaster_advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disaster_advisories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disaster_advisories_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_advisories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_advisories_zone_id'))

    op.drop_table('disaster_advisories')
    with op.batch_alter_table('chain_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_anchors_created_at'))

    op.drop_table('chain_anchors')
    # ### end Alembic commands ###
