"""add zone time_risk_curve column

Revision ID: c1a9e6f3b2d4
Revises: f571fc090c3e
Create Date: 2026-08-30 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a9e6f3b2d4'
down_revision: Union[str, Sequence[str], None] = 'f571fc090c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_risk_curve', sa.Text(), nullable=False,
                                       server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_column('time_risk_curve')

    # ### end Alembic commands ###
