"""add trip guardians, checkins, passport/consent/duress fields

Revision ID: c48eae9e1233
Revises: 818052a0f166
Create Date: 2026-08-31 03:49:36.034608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48eae9e1233'
down_revision: Union[str, Sequence[str], None] = '818052a0f166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('destination_name', sa.String(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lng', sa.Float(), nullable=True),
    sa.Column('expected_return_at', sa.DateTime(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_tourist_id'), ['tourist_id'], unique=False)

    op.create_table('trip_guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_contact', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_guardians_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_trip_guardians_tourist_id'), ['tourist_id'], unique=False)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('silent', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(), server_default='en', nullable=False))
        batch_op.add_column(sa.Column('data_retention_days', sa.Integer(), server_default='90', nullable=False))
        batch_op.add_column(sa.Column('duress_pin_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourists', schema=None) as batch_op:
        batch_op.drop_column('duress_pin_hash')
        batch_op.drop_column('data_retention_days')
        batch_op.drop_column('preferred_language')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('silent')

    with op.batch_alter_table('trip_guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_guardians_tourist_id'))
        batch_op.drop_index(batch_op.f('ix_trip_guardians_token'))

    op.drop_table('trip_guardians')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_tourist_id'))

    op.drop_table('checkins')
    # ### end Alembic commands ###
