"""add liveness_verifications table

Revision ID: eeff8a36fd36
Revises: 51c3b736eb77
Create Date: 2026-09-05 21:21:33.550040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeff8a36fd36'
down_revision: Union[str, Sequence[str], None] = '51c3b736eb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liveness_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=False),
    sa.Column('photo_sha256', sa.String(), nullable=False),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('liveness_score', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liveness_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liveness_verifications_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liveness_verifications_verification_token'), ['verification_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liveness_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liveness_verifications_verification_token'))
        batch_op.drop_index(batch_op.f('ix_liveness_verifications_session_id'))

    op.drop_table('liveness_verifications')
    # ### end Alembic commands ###
