"""add incident_transfers table

Revision ID: f13c10666939
Revises: 811145802bc1
Create Date: 2026-09-09 20:18:01.434617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13c10666939'
down_revision: Union[str, Sequence[str], None] = '811145802bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('responded_by', sa.String(), nullable=True),
    sa.Column('latest_lat', sa.Float(), nullable=True),
    sa.Column('latest_lng', sa.Float(), nullable=True),
    sa.Column('latest_location_at', sa.DateTime(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['police_stations.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_transfers_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_incident_transfers_incident_status', ['incident_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_transfers', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_transfers_incident_status')
        batch_op.drop_index(batch_op.f('ix_incident_transfers_incident_id'))

    op.drop_table('incident_transfers')
    # ### end Alembic commands ###
